[package]
name = "evolvers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
image = "0.24.6"
lazy_static = "1.4.0"
rand = "0.8.5"
rayon = "1.7.0"
